-- PARAMETERIZED CURSOR

DECLARE

CURSOR MY_EMP_LIST(P_DEPT_ID NUMBER) IS SELECT ES.EMP_NAME FROM EMPLOYEES ES WHERE ES.DEPT_ID = P_DEPT_ID;

LV_NAME VARCHAR2(100);

BEGIN

OPEN MY_EMP_LIST (10);
 LOOP
 FETCH MY_EMP_LIST INTO LV_NAME;
 EXIT WHEN MY_EMP_LIST%NOTFOUND;
 DBMS_OUTPUT.PUT_LINE('LV_NAME = ' || LV_NAME);
 END LOOP;
 CLOSE MY_EMP_LIST;
 END;

-- CURSOR FOR LOOP

DECLARE

V_NAME VARCHAR2(100);

BEGIN

FOR I IN (SELECT ES.EMP_NAME  FROM EMPLOYEES ES) LOOP
DBMS_OUTPUT.PUT_LINE(I.EMP_NAME);

END LOOP;

END;

-- METHOD 2

DECLARE

CURSOR EMP_NAME IS SELECT ES.EMP_NAME FROM EMPLOYEES ES;

LV_NAME VARCHAR2(50);

BEGIN

FOR I IN EMP_NAME LOOP
DBMS_OUTPUT.PUT_LINE(I.EMP_NAME);

END LOOP;

END;

-- REF CURSOR WEAKLY TYPE

DECLARE
TYPE MY_EMP_LIST IS REF CURSOR;
LV_EMP_LIST MY_EMP_LIST;
LV_NAME VARCHAR2(100);
--LV_ID NUMBER;

BEGIN

OPEN LV_EMP_LIST FOR SELECT ES.EMP_NAME FROM EMPLOYEES ES;

LOOP
FETCH LV_EMP_LIST INTO LV_NAME;
EXIT WHEN LV_EMP_LIST%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('LV_NAME = '|| LV_NAME);
END LOOP;
CLOSE LV_EMP_LIST;
END;

-- REF CURSOR STRONG TYPE

DECLARE
TYPE MY_EMP_LIST IS REF CURSOR RETURN EMPLOYEES%ROWTYPE;
LV_EMP_LIST MY_EMP_LIST;
LV_NAME EMPLOYEES%ROWTYPE;
--LV_ID NUMBER;

BEGIN

OPEN LV_EMP_LIST FOR SELECT * FROM EMPLOYEES ES;

LOOP
FETCH LV_EMP_LIST INTO LV_NAME;
EXIT WHEN LV_EMP_LIST%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('LV_NAME = '|| LV_NAME.EMP_NAME);
END LOOP;
CLOSE LV_EMP_LIST;
END;